7.post api articles article id comments
dave-hickman/news_project pull request #7
Opened 2023-05-11 14:20 UTC by dave-hickman

2023-05-11 15:01 UTC, Augs0 requested changes
Hey Dave, a great attempt so far. Just a few more tests to add to get this ticket up to where it needs to be, but a fab job so far!

2023-05-11 15:01 UTC, Augs0 commented on __tests__/app.test.js
> +        expect(typeof response.body.comment[0].author).toBe("string");
We would want to check for the actual values as we know them from the newComment variable

2023-05-11 15:01 UTC, Augs0 commented on __tests__/app.test.js
>    });
This isa great start but there are a number of other tests to consider here:

> what if I send through additional properties on my comment. We should ignore these
> what if I'm missing a property e.g. I don't send a body
> what if I use a username that doesn't exist?

2023-05-11 15:01 UTC, Augs0 commented on models/articles_model.js
> +          msg: `No user found for user_id: ${articleID}!`,
This doesn't seem to quite match up. You're talking about users and articles. Which one are we checking?

2023-05-11 15:01 UTC, Augs0 commented on playground.txt
> - comment_id |                                                                                         body                                                                                         | ar
We don't need to include this file in commits

2023-05-12 09:07 UTC, robert112233 requested changes
Amend the faulty test and submit another PR for review. Great work on Augusts' feedback!

2023-05-12 09:07 UTC, robert112233 commented on __tests__/app.test.js
> +      });
When August mentioned ignoring additional keys, we would still consider this a happy path. The extra keys will be ignored and a 201 status will be provided as normal. The user has done the _right_ thing, just with some additional _wrong_ things which can simply be ignored, so no error 👍

2023-05-12 09:07 UTC, robert112233 commented on models/articles_model.js
> +    })
We can remove this (see above comment) 😃

2023-05-12 09:25 UTC, robert112233 approved these changes
Great work , merge!

2023-05-12 09:29 UTC, merged